services:
  # Service PHP-FPM
  php:
    image: php:8.1-fpm
    container_name: symfony_php
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    environment:
      - DATABASE_URL=mysql://symfony:symfony@mysql:3306/symfony
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql &&
      docker-php-ext-enable pdo pdo_mysql &&
      php-fpm"
    depends_on:
      - mysql
  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
