services:
  # Service PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    environment:
      - DATABASE_URL=mysql://symfony:symfony@mysql:3306/symfony
    depends_on:
      - mysql
  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/ssl:/etc/mysql/ssl
    command: --ssl-ca=/etc/mysql/ssl/ca.pem --ssl-cert=/etc/mysql/ssl/server-cert.pem --ssl-key=/etc/mysql/ssl/server-key.pem
    ports:
      - "3307:3306"

volumes:
  mysql_data:
