sequenceDiagram
    Member->>+SnowTricks: visit the SnowTricks website
    SnowTricks-->>-Member: display the welcome page
    Member->>+SnowTricks: connect with his username and his password
    SnowTricks-->>-Member: display the welcome page with the button to delete a figure
    Member->>+SnowTricks: click on the button to delete a figure
    SnowTricks-->>-Member: display a popup to confirm the deletion
    Member->>+SnowTricks: click on a button in popup
    alt the user clicked on "yes"
    SnowTricks --x Member: display the welcome page without the deleted figure
    else the user clicked on "no"
    SnowTricks --x- Member: display the welcome page with all figures
    end