sequenceDiagram
    Member->>+SnowTricks: visit the site
    SnowTricks-->>-Member: display the welcome page with all figures
    Member->>+SnowTricks: click on button to sign in
    SnowTricks -->>- Member: display form to sign up with the forgotten password button
    Member ->>+ SnowTricks: click on button to forgotten password
    loop the username isn't valid and the form isn't submit
    SnowTricks-->>-Member: display the form with the errors
    Member->>+SnowTricks: fill the form to give a username
    end
    SnowTricks--x-Member: send mail to create a new password
