sequenceDiagram
    Member->>+SnowTricks: fill the form with his username to get a new password
    SnowTricks-->>-Member: send an email a link to reset password
    Member->>+SnowTricks: clik on link to reset his password
    loop the password isn't valid and the form isn't submit
    SnowTricks-->>-Member: display form to register a new password
    Member->>+SnowTricks: fill the form to give a username
    end
    SnowTricks --x- Member: display the welcome page